version: "3.3"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build: ./infra/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./app:/work/app

  web:
    build: ./infra/docker/nginx
    ports:
      - 8000:8000
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./app:/work/app

  db:
    build: ./infra/docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
